# render.yaml
# Deployment configuration for VotaYa on Render

services:
  # ---------- FRONTEND ----------
  - type: web
    name: frontend
    env: docker
    repo: https://github.com/Isaaidk/DeployPrueba.git
    branch: pruebadep
    dockerfilePath: Dockerfile
    dockerContext: VotaYa Digital Voting Platform
    healthCheck:
      path: /

  # ---------- AUTH SERVICE ----------
  - type: pserv
    name: auth-service
    env: docker
    repo: https://github.com/Isaaidk/DeployPrueba.git
    branch: pruebadep
    dockerfilePath: Dockerfile
    dockerContext: VotaYa-Backend/AuthService
    envVars:
      - key: SPRING_PROFILES_ACTIVE
        value: docker

  # ---------- VOTING SERVICE ----------
  - type: pserv
    name: voting-service
    env: docker
    repo: https://github.com/Isaaidk/DeployPrueba.git
    branch: pruebadep
    dockerfilePath: Dockerfile
    dockerContext: VotaYa-Backend/VotingService
    envVars:
      - key: SPRING_PROFILES_ACTIVE
        value: docker
      - key: RABBITMQ_HOST
        fromService:
          name: votaya-broker
          property: host

  # ---------- LEDGER SERVICE ----------
  - type: pserv
    name: ledger-service
    env: docker
    repo: https://github.com/Isaaidk/DeployPrueba.git
    branch: pruebadep
    dockerfilePath: Dockerfile
    dockerContext: VotaYa-Backend/LedgerService
    envVars:
      - key: SPRING_PROFILES_ACTIVE
        value: docker
      - key: RABBITMQ_HOST
        fromService:
          name: votaya-broker
          property: host
      - key: DB_HOST
        fromDatabase:
          name: votaya-db
          property: host

  # ---------- REPORT SERVICE ----------
  - type: pserv
    name: report-service
    env: docker
    repo: https://github.com/Isaaidk/DeployPrueba.git
    branch: pruebadep
    dockerfilePath: Dockerfile
    dockerContext: VotaYa-Backend/ReportService
    envVars:
      - key: SPRING_PROFILES_ACTIVE
        value: docker
      - key: DB_HOST
        fromDatabase:
          name: votaya-db
          property: host

  # ---------- RABBITMQ ----------
  - type: pserv
    name: votaya-broker
    env: docker
    image:
      url: rabbitmq:3.13-management-alpine

# ---------- POSTGRES DATABASE ----------
databases:
  - name: votaya-db
    databaseName: votayadb
    user: votaya
    plan: free
